### ISSUE TITLE
More on deploying a production server in README.md

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/admin_ui#28]
The title says it all: can you add a couple of sentences on how to deploy the built code on the actual server ? 

Which container ? Which directory ?

**Comment by miroslavKovacPantheon** [comment]
Done [here](https://github.com/YangCatalog/admin_ui/commit/b5b97df5757ed0be308344c5eb1f0755abb8943d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5), [here](https://github.com/YangCatalog/admin_ui/commit/262d9e0689b0d89f7fea4f8a353addb52be70dad#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5), [here](https://github.com/YangCatalog/admin_ui/commit/0848ae118e5f3d0aac5e8ed4362546df8bc2ff2f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) and [here](https://github.com/YangCatalog/admin_ui/commit/1f04dd232f5b139600cb56f525107d0f773dd594#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
