### ISSUE TITLE
Remove sub-second in registration date (API users management)

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/admin_ui#64]
The registration date in https://yangcatalog.org/admin/users-management displays looks like:
`2022-08-06 14:04:18.903437` while it should be `2022-08-06 14:04:18`

**Comment by rjsparks** [comment]
Be careful with the implementation here - Éric is not asking to change the data model (I think), but just the presentation in the admin. Consider solutions like https://stackoverflow.com/questions/7216764/in-the-django-admin-site-how-do-i-change-the-display-format-of-time-fields

**Comment by evyncke** [comment]
Thank you Robert, this is indeed my actual request.

**Comment by SlavomirMazurPantheon** [comment]
Hello,

issue fixed on the backend side - registration date is sent to the UI without milliseconds, but they are still preserved in the databse.

**Comment by evyncke** [comment]
Thank you, no problem of course to keep this 'detail' in the DB
